// ─── TRANSLATION STRINGS ────────────────────────────────────────
const S = {
  // NAV
  'nav.schedule':   { uk:'Записи',      en:'Schedule'   },
  'nav.bookings':   { uk:'Черга',        en:'Queue'      },
  'nav.queue':      { uk:'Черга',       en:'Queue'      },
  'nav.students':   { uk:'Учні',        en:'Students'   },
  'nav.services':   { uk:'Послуги',     en:'Services'   },
  'nav.chats':      { uk:'Чати',        en:'Chats'      },
  'nav.templates':  { uk:'Шаблони',     en:'Templates'  },
  'nav.stats':      { uk:'Статист.',    en:'Stats'      },
  'nav.settings':   { uk:'Налашт.',     en:'Settings'   },
  'nav.journal':    { uk:'Журнал',      en:'Journal'    },

  // COMMON
  'all':            { uk:'Всі',         en:'All'        },
  'save':           { uk:'Зберегти',    en:'Save'       },
  'cancel':         { uk:'Скасувати',   en:'Cancel'     },
  'delete':         { uk:'Видалити',    en:'Delete'     },
  'add':            { uk:'Додати',      en:'Add'        },
  'edit':           { uk:'Редагувати',  en:'Edit'       },
  'search':         { uk:'Пошук…',      en:'Search…'    },
  'loading':        { uk:'Завантаження…', en:'Loading…' },
  'none_found':     { uk:'Нічого не знайдено', en:'Nothing found' },
  'close':          { uk:'Закрити',     en:'Close'      },
  'call':           { uk:'Дзвонити',    en:'Call'       },
  'chat':           { uk:'Чат',         en:'Chat'       },
  'record':         { uk:'Запис',       en:'Booking'    },
  'block':          { uk:'Заблок.',     en:'Block'      },
  'unblock':        { uk:'Розблок.',    en:'Unblock'    },
  'blocked':        { uk:'Заблоковано', en:'Blocked'    },
  'copy':           { uk:'Копіювати',   en:'Copy'       },
  'on':             { uk:'Увімкнено',   en:'On'         },
  'off':            { uk:'Вимкнено',    en:'Off'        },
  'apply':          { uk:'Застосувати', en:'Apply'      },
  'send':           { uk:'Надіслати',   en:'Send'       },
  'active':         { uk:'Активних',    en:'Active'     },
  'archived':       { uk:'Архів',       en:'Archive'    },
  'school':         { uk:'Автошкола',   en:'Driving school' },
  'private':        { uk:'Приватний',   en:'Private'    },
  'hr':             { uk:'год',         en:'hr'         },
  'min':            { uk:'хв',          en:'min'        },
  'uah':            { uk:'₴',           en:'₴'          },
  'days':           { uk:'дн',          en:'days'       },
  'notes':          { uk:'Нотатки',     en:'Notes'      },
  'noshow':         { uk:'No-show',     en:'No-show'    },
  'lessons':        { uk:'Уроків',      en:'Lessons'    },
  'income':         { uk:'Дохід',       en:'Income'     },
  'rating':         { uk:'Рейтинг',     en:'Rating'     },
  'last_lesson':    { uk:'Ост. урок',   en:'Last lesson'},
  'total_hours':    { uk:'Годин',       en:'Hours'      },

  // STUDENTS
  'st.search_ph':   { uk:'Ім\'я або телефон…', en:'Name or phone…' },
  'st.count':       { uk:'учнів',       en:'students'   },
  'st.phone':       { uk:'Телефон',     en:'Phone'      },
  'st.discount':    { uk:'Знижка',      en:'Discount'   },
  'st.progress':    { uk:'Прогрес автошколи', en:'School progress' },
  'st.history':     { uk:'Історія записів', en:'Booking history' },
  'st.viber':       { uk:'Вайбер',      en:'Viber'      },
  'st.telegram':    { uk:'Телеграм',    en:'Telegram'   },
  'st.whatsapp':    { uk:'WhatsApp',    en:'WhatsApp'   },

  // BOOKINGS
  'bk.status.pending':   { uk:'Очікує',      en:'Pending'    },
  'bk.status.confirmed': { uk:'Підтверджено', en:'Confirmed'  },
  'bk.status.cancelled': { uk:'Скасовано',   en:'Cancelled'  },
  'bk.status.noshow':    { uk:'Не прийшов',  en:'No-show'    },
  'bk.confirm':     { uk:'Підтвердити',  en:'Confirm'    },
  'bk.cancel':      { uk:'Скасувати',   en:'Cancel'     },
  'bk.noshow':      { uk:'Не прийшов',  en:'No-show'    },
  'bk.today':       { uk:'Сьогодні',    en:'Today'      },
  'bk.tomorrow':    { uk:'Завтра',      en:'Tomorrow'   },
  'bk.week':        { uk:'Тиждень',     en:'Week'       },
  'bk.month':       { uk:'Місяць',      en:'Month'      },
  'bk.sort.date_asc':    { uk:'Дата ↑',      en:'Date ↑'     },
  'bk.sort.date_desc':   { uk:'Дата ↓',      en:'Date ↓'     },
  'bk.sort.name':        { uk:'Ім\'я А-Я',   en:'Name A-Z'   },
  'bk.sort.price':       { uk:'Сума ↓',      en:'Price ↓'    },
  'bk.group.date':       { uk:'По даті',     en:'By date'    },
  'bk.group.status':     { uk:'По статусу',  en:'By status'  },
  'bk.group.type':       { uk:'По типу',     en:'By type'    },
  'bk.pending_count':    { uk:'очікують',    en:'pending'    },
  'bk.total':            { uk:'Всього',      en:'Total'      },

  // CHATS
  'ch.chats':       { uk:'Чати',        en:'Chats'      },
  'ch.search_ph':   { uk:'Пошук контакту…', en:'Search contact…' },
  'ch.online':      { uk:'онлайн',      en:'online'     },
  'ch.offline':     { uk:'офлайн',      en:'offline'    },
  'ch.msg_ph':      { uk:'Повідомлення…', en:'Message…' },
  'ch.quick':       { uk:'Швидкі відповіді', en:'Quick replies' },
  'ch.q1':          { uk:'Підтверджую урок ✅', en:'Confirming lesson ✅' },
  'ch.q2':          { uk:'Урок скасовано ❌',   en:'Lesson cancelled ❌' },
  'ch.q3':          { uk:'Нагадую: завтра',      en:'Reminder: tomorrow' },
  'ch.q4':          { uk:'Будь ласка, підтвердіть', en:'Please confirm' },
  'ch.q5':          { uk:'До зустрічі 👋',        en:'See you 👋'         },

  // STATS
  'st2.week':        { uk:'Тиждень',    en:'Week'       },
  'st2.month':       { uk:'Місяць',     en:'Month'      },
  'st2.year':        { uk:'Рік',        en:'Year'       },
  'st2.dynamics':    { uk:'Динаміка',   en:'Dynamics'   },
  'st2.split':       { uk:'Розподіл',   en:'Split'      },
  'st2.by_day':      { uk:'По днях',    en:'By day'     },
  'st2.top5':        { uk:'Топ-5 учнів', en:'Top-5 students' },
  'st2.export':      { uk:'Експорт',    en:'Export'     },
  'st2.avg_check':   { uk:'Серед. чек', en:'Avg. check' },
  'st2.per_period':  { uk:'за період',  en:'per period' },
  'st2.per_lesson':  { uk:'дохід / урок', en:'per lesson' },

  // SERVICES
  'sv.title':        { uk:'Послуги',     en:'Services'   },
  'sv.active':       { uk:'Активних послуг', en:'Active services' },
  'sv.total_lessons':{ uk:'Уроків всього', en:'Total lessons' },
  'sv.drag_hint':    { uk:'тягни ☰ для зміни порядку', en:'drag ☰ to reorder' },
  'sv.add':          { uk:'Додати нову послугу', en:'Add new service' },
  'sv.edit_title':   { uk:'Редагування послуги', en:'Edit service' },
  'sv.new_title':    { uk:'Нова послуга', en:'New service' },
  'sv.duration':     { uk:'Тривалість',  en:'Duration'   },
  'sv.price':        { uk:'Ціна',        en:'Price'      },
  'sv.color':        { uk:'Колір слоту', en:'Slot color' },
  'sv.description':  { uk:'Опис',        en:'Description'},
  'sv.access':       { uk:'Доступ (категорії)', en:'Access (categories)' },
  'sv.delete_confirm':{ uk:'Видалити послугу?', en:'Delete service?' },
  'sv.archive':      { uk:'Архівувати',  en:'Archive'    },
  'sv.delete_forever':{ uk:'Видалити назавжди', en:'Delete forever' },
  'sv.preview':      { uk:'Попередній перегляд слоту', en:'Slot preview' },

  // TEMPLATES
  'tpl.title':       { uk:'Шаблони',     en:'Templates'  },
  'tpl.auto':        { uk:'Авто ⚡',     en:'Auto ⚡'    },
  'tpl.manual':      { uk:'Ручні ✋',    en:'Manual ✋'  },
  'tpl.active':      { uk:'Активних',    en:'Active'     },
  'tpl.send':        { uk:'Надіслати',   en:'Send'       },
  'tpl.new':         { uk:'Новий шаблон', en:'New template' },
  'tpl.edit_title':  { uk:'Редагування шаблону', en:'Edit template' },
  'tpl.name':        { uk:'Назва шаблону', en:'Template name' },
  'tpl.category':    { uk:'Категорія',   en:'Category'   },
  'tpl.channel':     { uk:'Канал',       en:'Channel'    },
  'tpl.trigger':     { uk:'Умова відправки', en:'Trigger' },
  'tpl.body':        { uk:'Текст повідомлення', en:'Message text' },
  'tpl.vars':        { uk:'Змінні — клікни щоб вставити:', en:'Variables — click to insert:' },
  'tpl.preview':     { uk:'Попередній перегляд', en:'Preview' },
  'tpl.to_whom':     { uk:'Кому надіслати', en:'Send to'  },
  'tpl.all_students':{ uk:'Всі учні',    en:'All students' },
  'tpl.edit_before': { uk:'Редагувати перед відправкою', en:'Edit before sending' },
  'tpl.not_found':   { uk:'Шаблонів не знайдено', en:'No templates found' },
  'tpl.create':      { uk:'Створити',    en:'Create'     },

  // SETTINGS SECTIONS
  'set.schedule.title':   { uk:'Робочий графік',       en:'Work Schedule'       },
  'set.schedule.info_t':  { uk:'Робочий час',           en:'Working hours'       },
  'set.schedule.info':    { uk:'Визначає робочі години інструктора. «Початок» і «Кінець» — загальні межі дня, за ними слоти учням не показуються. «Днів у розкладі» — скільки днів наперед видно в календарі одразу. «Блокувати минулі записи» — забороняє редагувати, переносити чи скасовувати записи, що вже минули (вони підсвічуються тьмяніше). Нижче — тижневий шаблон: для кожного дня можна зробити вихідний, задати власний час роботи та окрему обідню перерву — на цей час учні не зможуть записатись, у розкладі вона показується смугою «Обід».', en:'Sets the instructor\'s working hours. "Start" and "End" are the overall day limits — slots outside them are never shown to students. "Days shown" controls how many days ahead are visible in the calendar at once. "Lock past bookings" prevents editing, rescheduling or cancelling bookings that already happened (shown dimmed). Below is the weekly template: turn any day off, set its own working hours, and add a separate lunch break — students can\'t book during lunch, and it appears as a "Lunch" bar in the schedule.' },
  'set.schedule.start':   { uk:'Початок дня',           en:'Day start'           },
  'set.schedule.end':     { uk:'Кінець дня',            en:'Day end'             },
  'set.schedule.days':    { uk:'Днів у розкладі',       en:'Days shown'          },
  'set.schedule.hint_s':  { uk:'Перший доступний слот', en:'First available slot'},
  'set.schedule.hint_e':  { uk:'Останній слот',         en:'Last slot'           },
  'set.schedule.weekends':{ uk:'Вихідні дні',           en:'Weekends'            },
  'set.days':             { uk:'Пн,Вт,Ср,Чт,Пт,Сб,Нд', en:'Mo,Tu,We,Th,Fr,Sa,Su'},

  'set.lunch.title':  { uk:'Обідня перерва',  en:'Lunch break'    },
  'set.lunch.info_t': { uk:'Обідня перерва',  en:'Lunch break'    },
  'set.lunch.info':   { uk:'Заблокований часовий проміжок посередині дня. Учні не зможуть записатись на цей час. У розкладі він відображається смугою «Обід».', en:'A blocked time slot in the middle of the day. Students cannot book during this time. It appears as a "Lunch" bar in the schedule.' },
  'set.lunch.enable': { uk:'Увімкнути перерву', en:'Enable break'  },
  'set.lunch.from':   { uk:'З',               en:'From'           },
  'set.lunch.to':     { uk:'До',              en:'To'             },

  'set.snap.title':   { uk:'Крок часу',        en:'Time grid step' },
  'set.snap.info_t':  { uk:'Точність часу',    en:'Snap step'      },
  'set.snap.info':    { uk:'Точність сітки часу в розкладі. «Крок при перетягуванні» — округлює час, коли ти пересуваєш існуючий слот (15 хв — зручно для більшості, 5 хв — точніше, 30/60 хв — швидше). «Крок слота (довгий тап)» — з яким кроком створюється новий слот при довгому натисканні на порожньому місці розкладу. Кнопка «Очистити сирітські слоти» видаляє в базі позначки «зайнято», що залишились без активного запису (наприклад, після тестів чи помилки) по всіх датах одразу — безпечно і нічого корисного не зачіпає. Кнопка «Відновити позначки зайнятості» робить навпаки: дописує позначки зайнятості для всіх реальних активних записів, якщо вони десь загубились; нічого не видаляє.', en:'Time-grid precision in the schedule. "Drag snap step" rounds the time when you move an existing slot (15 min fits most cases, 5 min is more precise, 30/60 min is faster). "Slot step (long tap)" sets the step used when creating a new slot by long-pressing an empty spot. "Clean up orphaned slots" removes "busy" markers left in the database with no matching active booking (e.g. after testing or an error) across all dates at once — safe, it never touches valid data. "Restore occupied markers" does the opposite: it re-adds occupied markers for every real active booking if any went missing; it never deletes anything.' },
  'set.snap.label':   { uk:'Крок при перетягуванні', en:'Drag snap step' },

  'set.svc.title':    { uk:'Послуги та ціни', en:'Services & prices' },
  'set.svc.info_t':   { uk:'Послуги',         en:'Services'       },
  'set.svc.info':     { uk:'Кожна послуга — це тип уроку з тривалістю і ціною. Колір відображається прямо в слоті розкладу. Вимкнена послуга не доступна учням для запису.', en:'Each service is a lesson type with duration and price. The color appears directly in the schedule slot. A disabled service is unavailable for booking.' },
  'set.svc.duration_lbl': { uk:'Час (хв)',    en:'Time (min)'     },
  'set.svc.price_lbl':    { uk:'Ціна (₴)',    en:'Price (₴)'      },
  'set.svc.color':    { uk:'Колір слоту',      en:'Slot color'     },
  'set.svc.add':      { uk:'+ Додати послугу', en:'+ Add service'  },
  'set.svc.del':      { uk:'× Видалити послугу', en:'× Delete service' },

  'set.cat.title':    { uk:'Категорії учнів', en:'Student categories' },
  'set.cat.info_t':   { uk:'Для чого категорії?', en:'What are categories?' },
  'set.cat.info':     { uk:'Розділяють учнів за типом доступу. VIP бачить ексклюзивні послуги та слоти, Стандарт — базові. Категорія відображається на картці учня і у розкладі. Можна додати власну з будь-яким кольором.', en:'They group students by access level. VIP sees exclusive services and slots, Standard — basic ones. The category appears on the student card and in the schedule.' },
  'set.cat.color':    { uk:'Колір',            en:'Color'          },
  'set.cat.add':      { uk:'+ Додати категорію', en:'+ Add category' },
  'set.cat.new':      { uk:'Нова категорія',   en:'New category'   },

  'set.restr.title':  { uk:'Обмеження для учнів', en:'Student restrictions' },
  'set.restr.info_t': { uk:'Контроль записів',    en:'Booking control'     },
  'set.restr.info':   { uk:'Що учень може робити самостійно, без інструктора. «Учень може переносити/скасовувати» — окремі перемикачі, що дозволяють чи забороняють учню самому змінювати свій запис. «Заборона запису» — за скільки годин до уроку вже не можна записатись чи змінити запис. «Горизонт генерації слотів» — на скільки днів вперед кнопка-ключик у розкладі автоматично розставляє вільні слоти в базі. «Календар наперед (приватні)» — на скільки днів вперед учень-приватник бачить вільні слоти у своєму додатку. «Календар наперед (автошкола)» — те саме, але для учнів автошколи. «Мінімальний інтервал між записами» — мінімум днів, які мають пройти між двома будь-якими записами одного учня (0 — без обмеження) — захищає розклад від надто частих записів однієї людини.', en:'What a student can do on their own, without the instructor. "Student can reschedule/cancel" — separate toggles that allow or block a student from changing their own booking. "Booking cut-off" is how many hours before a lesson booking or changes are no longer allowed. "Slot generation horizon" is how many days ahead the schedule\'s key-button auto-fills free slots in the database. "Calendar ahead (private)" is how many days ahead a private-lesson student sees free slots in their app. "Calendar ahead (school)" is the same for school students. "Min interval between bookings" is the minimum number of days required between any two bookings of the same student (0 — no limit), protecting the schedule from too-frequent bookings by one person.' },
  'set.restr.reschedule': { uk:'Учень може переносити букінг', en:'Student can reschedule' },
  'set.restr.cancel':     { uk:'Учень може скасовувати',       en:'Student can cancel'     },
  'set.restr.cutoff':     { uk:'Заборона запису',               en:'Booking cut-off'        },
  'set.restr.cutoff_h':   { uk:'Годин до уроку',                en:'Hours before lesson'    },
  'set.restr.slotGen':    { uk:'Горизонт генерації слотів',      en:'Slot generation horizon' },
  'set.restr.slotGen_h':  { uk:'На скільки днів вперед кнопка-ключик у розкладі розставляє вільні слоти', en:'How many days ahead the schedule key-button auto-fills free slots' },
  'set.restr.calendar':   { uk:'Календар наперед (приватні)',   en:'Calendar ahead (private)' },
  'set.restr.calendar_h': { uk:'Днів видно учневі-приватнику',  en:'Days visible to a private-lesson student' },
  'set.restr.schoolCalendar':   { uk:'Календар наперед (автошкола)', en:'Calendar ahead (school)' },
  'set.restr.schoolCalendar_h': { uk:'Днів видно учневі автошколи',  en:'Days visible to school student' },

  'set.queue.title':  { uk:'Черга', en:'Queue' },
  'set.queue.info_t': { uk:'Черга', en:'Queue' },
  'set.queue.info':   { uk:'Черга спрацьовує, коли учень хоче записатись на зайнятий слот, або коли слот звільняється і потрібно вирішити, хто його отримає. «Вимагати підтвердження» — нові букінги одразу отримують статус «Очікує» замість автоматичного підтвердження. Режими черги: «Автоматично» — місце дістається тому, хто став в черзі першим. «Розсилка» — пропозиція надсилається одночасно всім у черзі, місце отримує той, хто підтвердив швидше. «Вручну» — інструктор сам переглядає список охочих і вирішує, кого запросити на звільнене місце.', en:'The queue kicks in when a student wants a slot that\'s already taken, or when a slot frees up and someone needs to get it. "Require confirmation" makes new bookings start in "Pending" status instead of being confirmed automatically. Queue modes: "FIFO" — the spot goes to whoever joined the queue first. "Broadcast" — the offer is sent to everyone in the queue at once, and the first to confirm gets the spot. "Manual" — the instructor reviews the list of interested students and personally decides who gets the freed slot.' },
  'set.queue.require':{ uk:'Вимагати підтвердження',        en:'Require confirmation'   },
  'set.queue.require_h':{ uk:'Нові букінги отримують статус «Очікує»', en:'New bookings get "Pending" status' },
  'set.queue.mode':   { uk:'Режим черги',                    en:'Queue mode'             },
  'set.queue.fifo':   { uk:'Автоматично',                    en:'FIFO'                   },
  'set.queue.fifo_h': { uk:'Перший хто записався — отримує місце автоматично', en:'First registered gets the spot automatically' },
  'set.queue.bc':     { uk:'Розсилка',                       en:'Broadcast'              },
  'set.queue.bc_h':   { uk:'Розсилка всім — хто перший підтвердить, той записаний', en:'Sent to all — first to confirm gets booked' },
  'set.queue.manual': { uk:'Вручну',                          en:'Manual'                 },
  'set.queue.manual_h':{ uk:'Інструктор сам обирає кого запросити', en:'Instructor chooses who to invite' },

  'set.sticky.title': { uk:'Вільні слоти поряд із записом', en:'Free slots near booking' },
  'set.sticky.info_t':{ uk:'Як це працює', en:'How it works' },
  'set.sticky.info':  { uk:'Коли увімкнено — учень бачить лише вільні слоти, що межують із записом (уроком) або з обідньою перервою. Поодинокі вільні години "в проміжку", без сусіднього запису чи обіду з жодного боку, — ховаються, щоб розклад не дробився на незручні залишки. Приклад: є запис на 12:00–14:00 → слот до нього (11:00) покажеться лише якщо обрано "До" або "Обидва", слот після (14:00) — лише якщо "Після" або "Обидва". Обід враховується за тим самим правилом: слот прямо перед обідом і слот прямо після обіду підпорядковані тому ж вибору. Перший вільний слот дня показується завжди, незалежно від налаштування. Коли вимкнено — учень бачить усі вільні слоти без обмежень.', en:'When enabled, the student only sees free slots adjacent to an existing booking (a lesson) or to the lunch break. A lone free hour "in the middle", with no neighboring booking or lunch on either side, is hidden — so the schedule doesn\'t fragment into awkward leftovers. Example: there\'s a booking 12:00–14:00 → the slot before it (11:00) shows only if "Before" or "Both" is selected, the slot after (14:00) — only if "After" or "Both". Lunch follows the same rule: the slot right before lunch and the slot right after lunch obey the same choice. The very first free slot of the day always shows, regardless of the setting. When disabled, the student sees all free slots with no restriction.' },
  'set.sticky.before':{ uk:'Тільки перед записом',      en:'Only before booking'    },
  'set.sticky.after': { uk:'Тільки після запису',       en:'Only after booking'     },
  'set.sticky.both':  { uk:'Обидва — учень обирає сам', en:'Both — student chooses' },

  'set.auto.title':   { uk:'Авто-повідомлення',     en:'Auto messages'          },
  'set.auto.info_t':  { uk:'Автоматичні повідомлення', en:'Automatic messages'   },
  'set.auto.info':    { uk:'Повідомлення, які система надсилає учням автоматично, без твоєї участі. Тексти самих повідомлень редагуються у вкладці «Шаблони». «Нагадування» — можна додати кілька, кожне надсилається за вказану кількість годин до уроку (наприклад, за 24 і за 2 години) — зменшує кількість пропущених занять. «Автоматичне скасування» — якщо учень не підтвердив запис, система сама скасовує його. «Автозапит з черги» — коли звільняється слот, система сама пропонує його наступному в черзі, без ручного втручання інструктора.', en:'Messages the system sends to students automatically, without your involvement. Edit the message text itself in the Templates tab. "Reminder" — you can add several, each sent a set number of hours before the lesson (e.g. 24h and 2h before) — reduces missed lessons. "Auto-cancel" — if a student doesn\'t confirm a booking, the system cancels it automatically. "Auto queue offer" — when a slot frees up, the system automatically offers it to the next student in the queue, with no manual action from the instructor.' },
  'set.auto.reminder':{ uk:'Нагадування',            en:'Reminder'               },
  'set.auto.rem_h':   { uk:'год до уроку',            en:'hr before lesson'       },
  'set.auto.welcome': { uk:'Вітання новому учневі',   en:'Welcome new student'    },
  'set.auto.confirm': { uk:'Підтвердження букінгу',   en:'Booking confirmation'   },
  'set.auto.cancel':  { uk:'Повідомлення про скасування', en:'Cancellation notice'},
  'set.auto.queue':   { uk:'Пропозиція з черги',      en:'Queue offer'            },

  'set.nav.title':    { uk:'Нижня навігація',  en:'Bottom navigation'  },
  'set.nav.info_t':   { uk:'Вкладки меню',     en:'Menu tabs'          },
  'set.nav.info':     { uk:'Вибери які вкладки показувати в нижній панелі. Вимкнені вкладки зникають з меню але залишаються доступними. «Налаштування» завжди активні.', en:'Choose which tabs to show in the bottom bar. Disabled tabs disappear from the menu but remain accessible. "Settings" is always visible.' },

  'set.look.title':   { uk:'Зовнішній вигляд', en:'Appearance'         },
  'set.look.info_t':  { uk:'Тема і мова',       en:'Theme and language' },
  'set.look.info':    { uk:'Темна тема зручна для роботи вночі або в слабоосвітленому місці. Мова впливає на текст у системних повідомленнях і кнопках учнівського додатку.', en:'Dark theme is great for working at night or in low light. Language affects text in system messages and buttons in the student app.' },
  'set.look.theme':   { uk:'Тема',              en:'Theme'              },
  'set.look.dark':    { uk:'Темна',             en:'Dark'               },
  'set.look.light':   { uk:'Світла',            en:'Light'              },
  'set.look.lang':    { uk:'Мова',              en:'Language'           },
};

export const createT = lang => key => {
  const entry = S[key];
  if (!entry) return key;
  return entry[lang] || entry.uk || key;
};

// Global language (for components that don't receive lang prop)
export let globalLang = localStorage.getItem('id4lang') || 'uk';
export const setGlobalLang = l => { globalLang = l; localStorage.setItem('id4lang', l); };
export const T = key => createT(globalLang)(key);
