// ─── TRANSLATION STRINGS ────────────────────────────────────────
const S = {
  // NAV
  'nav.schedule':   { uk:'Записи',      en:'Schedule'   },
  'nav.bookings':   { uk:'Букінги',     en:'Bookings'   },
  'nav.students':   { uk:'Учні',        en:'Students'   },
  'nav.services':   { uk:'Послуги',     en:'Services'   },
  'nav.chats':      { uk:'Чати',        en:'Chats'      },
  'nav.templates':  { uk:'Шаблони',     en:'Templates'  },
  'nav.stats':      { uk:'Статист.',    en:'Stats'      },
  'nav.settings':   { uk:'Налашт.',     en:'Settings'   },

  // COMMON
  'all':            { uk:'Всі',         en:'All'        },
  'save':           { uk:'Зберегти',    en:'Save'       },
  'cancel':         { uk:'Скасувати',   en:'Cancel'     },
  'delete':         { uk:'Видалити',    en:'Delete'     },
  'add':            { uk:'Додати',      en:'Add'        },
  'edit':           { uk:'Редагувати',  en:'Edit'       },
  'search':         { uk:'Пошук…',      en:'Search…'    },
  'loading':        { uk:'Завантаження…', en:'Loading…' },
  'none_found':     { uk:'Нічого не знайдено', en:'Nothing found' },
  'close':          { uk:'Закрити',     en:'Close'      },
  'call':           { uk:'Дзвонити',    en:'Call'       },
  'chat':           { uk:'Чат',         en:'Chat'       },
  'record':         { uk:'Запис',       en:'Booking'    },
  'block':          { uk:'Заблок.',     en:'Block'      },
  'unblock':        { uk:'Розблок.',    en:'Unblock'    },
  'blocked':        { uk:'Заблоковано', en:'Blocked'    },
  'copy':           { uk:'Копіювати',   en:'Copy'       },
  'on':             { uk:'Увімкнено',   en:'On'         },
  'off':            { uk:'Вимкнено',    en:'Off'        },
  'apply':          { uk:'Застосувати', en:'Apply'      },
  'send':           { uk:'Надіслати',   en:'Send'       },
  'active':         { uk:'Активних',    en:'Active'     },
  'archived':       { uk:'Архів',       en:'Archive'    },
  'school':         { uk:'Автошкола',   en:'Driving school' },
  'private':        { uk:'Приватний',   en:'Private'    },
  'hr':             { uk:'год',         en:'hr'         },
  'min':            { uk:'хв',          en:'min'        },
  'uah':            { uk:'₴',           en:'₴'          },
  'days':           { uk:'дн',          en:'days'       },
  'notes':          { uk:'Нотатки',     en:'Notes'      },
  'noshow':         { uk:'No-show',     en:'No-show'    },
  'lessons':        { uk:'Уроків',      en:'Lessons'    },
  'income':         { uk:'Дохід',       en:'Income'     },
  'rating':         { uk:'Рейтинг',     en:'Rating'     },
  'last_lesson':    { uk:'Ост. урок',   en:'Last lesson'},
  'total_hours':    { uk:'Годин',       en:'Hours'      },

  // STUDENTS
  'st.search_ph':   { uk:'Ім\'я або телефон…', en:'Name or phone…' },
  'st.count':       { uk:'учнів',       en:'students'   },
  'st.phone':       { uk:'Телефон',     en:'Phone'      },
  'st.discount':    { uk:'Знижка',      en:'Discount'   },
  'st.progress':    { uk:'Прогрес автошколи', en:'School progress' },
  'st.history':     { uk:'Історія записів', en:'Booking history' },
  'st.viber':       { uk:'Вайбер',      en:'Viber'      },
  'st.telegram':    { uk:'Телеграм',    en:'Telegram'   },
  'st.whatsapp':    { uk:'WhatsApp',    en:'WhatsApp'   },

  // BOOKINGS
  'bk.status.pending':   { uk:'Очікує',      en:'Pending'    },
  'bk.status.confirmed': { uk:'Підтверджено', en:'Confirmed'  },
  'bk.status.cancelled': { uk:'Скасовано',   en:'Cancelled'  },
  'bk.status.noshow':    { uk:'Не прийшов',  en:'No-show'    },
  'bk.confirm':     { uk:'Підтвердити',  en:'Confirm'    },
  'bk.cancel':      { uk:'Скасувати',   en:'Cancel'     },
  'bk.noshow':      { uk:'Не прийшов',  en:'No-show'    },
  'bk.today':       { uk:'Сьогодні',    en:'Today'      },
  'bk.tomorrow':    { uk:'Завтра',      en:'Tomorrow'   },
  'bk.week':        { uk:'Тиждень',     en:'Week'       },
  'bk.month':       { uk:'Місяць',      en:'Month'      },
  'bk.sort.date_asc':    { uk:'Дата ↑',      en:'Date ↑'     },
  'bk.sort.date_desc':   { uk:'Дата ↓',      en:'Date ↓'     },
  'bk.sort.name':        { uk:'Ім\'я А-Я',   en:'Name A-Z'   },
  'bk.sort.price':       { uk:'Сума ↓',      en:'Price ↓'    },
  'bk.group.date':       { uk:'По даті',     en:'By date'    },
  'bk.group.status':     { uk:'По статусу',  en:'By status'  },
  'bk.group.type':       { uk:'По типу',     en:'By type'    },
  'bk.pending_count':    { uk:'очікують',    en:'pending'    },
  'bk.total':            { uk:'Всього',      en:'Total'      },

  // CHATS
  'ch.chats':       { uk:'Чати',        en:'Chats'      },
  'ch.search_ph':   { uk:'Пошук контакту…', en:'Search contact…' },
  'ch.online':      { uk:'онлайн',      en:'online'     },
  'ch.offline':     { uk:'офлайн',      en:'offline'    },
  'ch.msg_ph':      { uk:'Повідомлення…', en:'Message…' },
  'ch.quick':       { uk:'Швидкі відповіді', en:'Quick replies' },
  'ch.q1':          { uk:'Підтверджую урок ✅', en:'Confirming lesson ✅' },
  'ch.q2':          { uk:'Урок скасовано ❌',   en:'Lesson cancelled ❌' },
  'ch.q3':          { uk:'Нагадую: завтра',      en:'Reminder: tomorrow' },
  'ch.q4':          { uk:'Будь ласка, підтвердіть', en:'Please confirm' },
  'ch.q5':          { uk:'До зустрічі 👋',        en:'See you 👋'         },

  // STATS
  'st2.week':        { uk:'Тиждень',    en:'Week'       },
  'st2.month':       { uk:'Місяць',     en:'Month'      },
  'st2.year':        { uk:'Рік',        en:'Year'       },
  'st2.dynamics':    { uk:'Динаміка',   en:'Dynamics'   },
  'st2.split':       { uk:'Розподіл',   en:'Split'      },
  'st2.by_day':      { uk:'По днях',    en:'By day'     },
  'st2.top5':        { uk:'Топ-5 учнів', en:'Top-5 students' },
  'st2.export':      { uk:'Експорт',    en:'Export'     },
  'st2.avg_check':   { uk:'Серед. чек', en:'Avg. check' },
  'st2.per_period':  { uk:'за період',  en:'per period' },
  'st2.per_lesson':  { uk:'дохід / урок', en:'per lesson' },

  // SERVICES
  'sv.title':        { uk:'Послуги',     en:'Services'   },
  'sv.active':       { uk:'Активних послуг', en:'Active services' },
  'sv.total_lessons':{ uk:'Уроків всього', en:'Total lessons' },
  'sv.drag_hint':    { uk:'тягни ☰ для зміни порядку', en:'drag ☰ to reorder' },
  'sv.add':          { uk:'Додати нову послугу', en:'Add new service' },
  'sv.edit_title':   { uk:'Редагування послуги', en:'Edit service' },
  'sv.new_title':    { uk:'Нова послуга', en:'New service' },
  'sv.duration':     { uk:'Тривалість',  en:'Duration'   },
  'sv.price':        { uk:'Ціна',        en:'Price'      },
  'sv.color':        { uk:'Колір слоту', en:'Slot color' },
  'sv.description':  { uk:'Опис',        en:'Description'},
  'sv.access':       { uk:'Доступ (категорії)', en:'Access (categories)' },
  'sv.delete_confirm':{ uk:'Видалити послугу?', en:'Delete service?' },
  'sv.archive':      { uk:'Архівувати',  en:'Archive'    },
  'sv.delete_forever':{ uk:'Видалити назавжди', en:'Delete forever' },
  'sv.preview':      { uk:'Попередній перегляд слоту', en:'Slot preview' },

  // TEMPLATES
  'tpl.title':       { uk:'Шаблони',     en:'Templates'  },
  'tpl.auto':        { uk:'Авто ⚡',     en:'Auto ⚡'    },
  'tpl.manual':      { uk:'Ручні ✋',    en:'Manual ✋'  },
  'tpl.active':      { uk:'Активних',    en:'Active'     },
  'tpl.send':        { uk:'Надіслати',   en:'Send'       },
  'tpl.new':         { uk:'Новий шаблон', en:'New template' },
  'tpl.edit_title':  { uk:'Редагування шаблону', en:'Edit template' },
  'tpl.name':        { uk:'Назва шаблону', en:'Template name' },
  'tpl.category':    { uk:'Категорія',   en:'Category'   },
  'tpl.channel':     { uk:'Канал',       en:'Channel'    },
  'tpl.trigger':     { uk:'Умова відправки', en:'Trigger' },
  'tpl.body':        { uk:'Текст повідомлення', en:'Message text' },
  'tpl.vars':        { uk:'Змінні — клікни щоб вставити:', en:'Variables — click to insert:' },
  'tpl.preview':     { uk:'Попередній перегляд', en:'Preview' },
  'tpl.to_whom':     { uk:'Кому надіслати', en:'Send to'  },
  'tpl.all_students':{ uk:'Всі учні',    en:'All students' },
  'tpl.edit_before': { uk:'Редагувати перед відправкою', en:'Edit before sending' },
  'tpl.not_found':   { uk:'Шаблонів не знайдено', en:'No templates found' },
  'tpl.create':      { uk:'Створити',    en:'Create'     },

  // SETTINGS SECTIONS
  'set.schedule.title':   { uk:'Робочий графік',       en:'Work Schedule'       },
  'set.schedule.info_t':  { uk:'Робочий час',           en:'Working hours'       },
  'set.schedule.info':    { uk:'Визначає коли учні можуть записуватись. Поза робочим часом слоти не відображаються. Вихідні дні повністю блокуються в календарі.', en:'Defines when students can book. Slots outside working hours are hidden. Weekend days are fully blocked in the calendar.' },
  'set.schedule.start':   { uk:'Початок дня',           en:'Day start'           },
  'set.schedule.end':     { uk:'Кінець дня',            en:'Day end'             },
  'set.schedule.days':    { uk:'Днів у розкладі',       en:'Days shown'          },
  'set.schedule.hint_s':  { uk:'Перший доступний слот', en:'First available slot'},
  'set.schedule.hint_e':  { uk:'Останній слот',         en:'Last slot'           },
  'set.schedule.weekends':{ uk:'Вихідні дні',           en:'Weekends'            },
  'set.days':             { uk:'Пн,Вт,Ср,Чт,Пт,Сб,Нд', en:'Mo,Tu,We,Th,Fr,Sa,Su'},

  'set.lunch.title':  { uk:'Обідня перерва',  en:'Lunch break'    },
  'set.lunch.info_t': { uk:'Обідня перерва',  en:'Lunch break'    },
  'set.lunch.info':   { uk:'Заблокований часовий проміжок посередині дня. Учні не зможуть записатись на цей час. У розкладі він відображається смугою «Обід».', en:'A blocked time slot in the middle of the day. Students cannot book during this time. It appears as a "Lunch" bar in the schedule.' },
  'set.lunch.enable': { uk:'Увімкнути перерву', en:'Enable break'  },
  'set.lunch.from':   { uk:'З',               en:'From'           },
  'set.lunch.to':     { uk:'До',              en:'To'             },

  'set.snap.title':   { uk:'Крок сітки часу', en:'Time grid step' },
  'set.snap.info_t':  { uk:'Крок прив\'язки', en:'Snap step'      },
  'set.snap.info':    { uk:'При перетягуванні слотів у розкладі час «прилипає» до найближчого кроку. 15 хв — зручно для більшості. 5 хв — точніше. 30 хв — швидше.', en:'When dragging slots, time "snaps" to the nearest step. 15 min — works for most. 5 min — more precise. 30 min — faster.' },
  'set.snap.label':   { uk:'Крок при перетягуванні', en:'Drag snap step' },

  'set.svc.title':    { uk:'Послуги та ціни', en:'Services & prices' },
  'set.svc.info_t':   { uk:'Послуги',         en:'Services'       },
  'set.svc.info':     { uk:'Кожна послуга — це тип уроку з тривалістю і ціною. Колір відображається прямо в слоті розкладу. Вимкнена послуга не доступна учням для запису.', en:'Each service is a lesson type with duration and price. The color appears directly in the schedule slot. A disabled service is unavailable for booking.' },
  'set.svc.duration_lbl': { uk:'Час (хв)',    en:'Time (min)'     },
  'set.svc.price_lbl':    { uk:'Ціна (₴)',    en:'Price (₴)'      },
  'set.svc.color':    { uk:'Колір слоту',      en:'Slot color'     },
  'set.svc.add':      { uk:'+ Додати послугу', en:'+ Add service'  },
  'set.svc.del':      { uk:'× Видалити послугу', en:'× Delete service' },

  'set.cat.title':    { uk:'Категорії учнів', en:'Student categories' },
  'set.cat.info_t':   { uk:'Для чого категорії?', en:'What are categories?' },
  'set.cat.info':     { uk:'Розділяють учнів за типом доступу. VIP бачить ексклюзивні послуги та слоти, Стандарт — базові. Категорія відображається на картці учня і у розкладі. Можна додати власну з будь-яким кольором.', en:'They group students by access level. VIP sees exclusive services and slots, Standard — basic ones. The category appears on the student card and in the schedule.' },
  'set.cat.color':    { uk:'Колір',            en:'Color'          },
  'set.cat.add':      { uk:'+ Додати категорію', en:'+ Add category' },
  'set.cat.new':      { uk:'Нова категорія',   en:'New category'   },

  'set.restr.title':  { uk:'Обмеження для учнів', en:'Student restrictions' },
  'set.restr.info_t': { uk:'Контроль записів',    en:'Booking control'     },
  'set.restr.info':   { uk:'Визначає що учні можуть робити самостійно. Заборона запису — мінімум годин до уроку коли не можна вже записатись. Календар наперед — скільки днів вперед учень бачить вільні слоти.', en:'Defines what students can do on their own. Cut-off — minimum hours before a lesson when booking is no longer allowed. Calendar ahead — how many days forward the student can see free slots.' },
  'set.restr.reschedule': { uk:'Учень може переносити букінг', en:'Student can reschedule' },
  'set.restr.cancel':     { uk:'Учень може скасовувати',       en:'Student can cancel'     },
  'set.restr.cutoff':     { uk:'Заборона запису',               en:'Booking cut-off'        },
  'set.restr.cutoff_h':   { uk:'Годин до уроку',                en:'Hours before lesson'    },
  'set.restr.calendar':   { uk:'Календар наперед',              en:'Calendar ahead'         },
  'set.restr.calendar_h': { uk:'Днів видно учневі',             en:'Days visible to student'},

  'set.queue.title':  { uk:'Підтвердження & черга', en:'Confirmation & queue' },
  'set.queue.info_t': { uk:'Підтвердження і черга', en:'Confirmation and queue' },
  'set.queue.info':   { uk:'Якщо підтвердження увімкнено — новий запис одразу не діє, ти маєш його підтвердити вручну. Черга: FIFO — перший хто записався отримує місце, Broadcast — хто швидше підтвердив, Вручну — ти обираєш сам.', en:'If confirmation is on — a new booking is pending until you confirm it manually. Queue: FIFO — first registered gets the spot, Broadcast — first to confirm wins, Manual — you choose.' },
  'set.queue.require':{ uk:'Вимагати підтвердження',        en:'Require confirmation'   },
  'set.queue.require_h':{ uk:'Нові букінги отримують статус «Очікує»', en:'New bookings get "Pending" status' },
  'set.queue.mode':   { uk:'Режим черги',                    en:'Queue mode'             },
  'set.queue.fifo':   { uk:'FIFO',                            en:'FIFO'                   },
  'set.queue.fifo_h': { uk:'Перший хто записався — отримує місце автоматично', en:'First registered gets the spot automatically' },
  'set.queue.bc':     { uk:'Broadcast',                       en:'Broadcast'              },
  'set.queue.bc_h':   { uk:'Розсилка всім — хто перший підтвердить, той записаний', en:'Sent to all — first to confirm gets booked' },
  'set.queue.manual': { uk:'Вручну',                          en:'Manual'                 },
  'set.queue.manual_h':{ uk:'Інструктор сам обирає кого запросити', en:'Instructor chooses who to invite' },

  'set.sticky.title': { uk:'Прилипання вільних слотів', en:'Free slot sticky' },
  'set.sticky.info_t':{ uk:'Як показувати вільний час?', en:'How to show free time?' },
  'set.sticky.info':  { uk:'Якщо є запис на 12:00–14:00, а учень хоче 1 годину — які слоти йому показати? "До" — тільки 11:00, "Після" — тільки 14:00, "Обидва" — учень обирає сам. Рекомендується "Обидва" для максимальної гнучкості.', en:'If there\'s a booking 12:00–14:00 and a student wants 1 hour — which slots to show? "Before" — only 11:00, "After" — only 14:00, "Both" — student chooses. "Both" recommended for max flexibility.' },
  'set.sticky.before':{ uk:'Тільки попередній слот',    en:'Only previous slot'     },
  'set.sticky.after': { uk:'Тільки наступний слот',     en:'Only next slot'         },
  'set.sticky.both':  { uk:'Обидва — вибір учня',       en:'Both — student chooses' },

  'set.auto.title':   { uk:'Авто-повідомлення',     en:'Auto messages'          },
  'set.auto.info_t':  { uk:'Автоматичні повідомлення', en:'Automatic messages'   },
  'set.auto.info':    { uk:'Система надсилає повідомлення учням без твоєї участі. Тексти налаштовуються у вкладці «Шаблони». Нагадування зменшує кількість no-show, вітання справляє добре перше враження.', en:'The system sends messages to students automatically. Edit text in the Templates tab. Reminders reduce no-shows, welcome messages create great first impressions.' },
  'set.auto.reminder':{ uk:'Нагадування',            en:'Reminder'               },
  'set.auto.rem_h':   { uk:'год до уроку',            en:'hr before lesson'       },
  'set.auto.welcome': { uk:'Вітання новому учневі',   en:'Welcome new student'    },
  'set.auto.confirm': { uk:'Підтвердження букінгу',   en:'Booking confirmation'   },
  'set.auto.cancel':  { uk:'Повідомлення про скасування', en:'Cancellation notice'},
  'set.auto.queue':   { uk:'Пропозиція з черги',      en:'Queue offer'            },

  'set.nav.title':    { uk:'Нижня навігація',  en:'Bottom navigation'  },
  'set.nav.info_t':   { uk:'Вкладки меню',     en:'Menu tabs'          },
  'set.nav.info':     { uk:'Вибери які вкладки показувати в нижній панелі. Вимкнені вкладки зникають з меню але залишаються доступними. «Налаштування» завжди активні.', en:'Choose which tabs to show in the bottom bar. Disabled tabs disappear from the menu but remain accessible. "Settings" is always visible.' },

  'set.look.title':   { uk:'Зовнішній вигляд', en:'Appearance'         },
  'set.look.info_t':  { uk:'Тема і мова',       en:'Theme and language' },
  'set.look.info':    { uk:'Темна тема зручна для роботи вночі або в слабоосвітленому місці. Мова впливає на текст у системних повідомленнях і кнопках учнівського додатку.', en:'Dark theme is great for working at night or in low light. Language affects text in system messages and buttons in the student app.' },
  'set.look.theme':   { uk:'Тема',              en:'Theme'              },
  'set.look.dark':    { uk:'Темна',             en:'Dark'               },
  'set.look.light':   { uk:'Світла',            en:'Light'              },
  'set.look.lang':    { uk:'Мова',              en:'Language'           },
};

export const createT = lang => key => {
  const entry = S[key];
  if (!entry) return key;
  return entry[lang] || entry.uk || key;
};

// Global language (for components that don't receive lang prop)
export let globalLang = localStorage.getItem('id4lang') || 'uk';
export const setGlobalLang = l => { globalLang = l; localStorage.setItem('id4lang', l); };
export const T = key => createT(globalLang)(key);
